config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  patch 'edit_color_preference', to: 'users#edit_color_preference'
  root to: 'pages#home'

  resources :to_do_lists, except: [ :show ] do
    resources :tasks, only: [ :new, :create ]
  end

  resources :tasks, only: [ :destroy, :edit, :update ] do
    patch 'done', to: 'tasks#done'
  end

  resources :long_notes do
    patch 'set_public', to: 'long_notes#set_public'
  end

  resources :objectives
  # resources :missions
  resources :short_notes
  resources :bookmarks
  resources :posts
end

app/models/long_note.rb
class LongNote < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  has_many_attached :images
  has_rich_text :description
end

app/controllers/long_notes_controller.rb
class LongNotesController < ApplicationController
  before_action :set_long_note, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @message = ""
    if params[:query].present?
      sql_query = " \
        long_notes.description ILIKE :query \
        OR long_notes.title ILIKE :query \
      "
      @long_notes = policy_scope(LongNote).where(sql_query, query: "%#{params[:query]}%").with_rich_text_description_and_embeds
      @message = "⚠️ Aucune note ne correspond à votre recherche. ⚠️" if @long_notes.count == 0
    else
      @long_notes = policy_scope(LongNote).order(updated_at: :desc).with_rich_text_description_and_embeds
    end
    if params[:id]
      @long_note = LongNote.find(params[:id])
    else
      @long_note = @long_notes.first
    end
  end

  def show
  end

  def new
    @long_note = LongNote.new
    @long_note.user = current_user
    authorize @long_note
  end

  def create
    @long_note = LongNote.new(long_note_params)
    @long_note.user = current_user
    authorize @long_note

    if @long_note.save
      redirect_to long_notes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @long_note.update(long_note_params)

    if @long_note.save
      redirect_to long_notes_path
    else
      render :edit
    end
  end

  def set_public
    @long_note = LongNote.find(params[:long_note_id])
    authorize @long_note
    if @long_note.update_attribute(:publicly_displayed, publicly_displayed)
      redirect_to long_notes_path, notice: if @long_note.publicly_displayed then "This one is public now. You can share it!" else "Set as private." end
    else
      render :edit
    end
  end

  def destroy
    @long_note.destroy
    redirect_to long_notes_path
  end

  private

  def publicly_displayed
    @long_note.publicly_displayed ? @long_note.publicly_displayed = false : @long_note.publicly_displayed = true
  end

  def set_long_note
    @long_note = LongNote.find(params[:id])
    authorize @long_note
  end

  def long_note_params
    params.require(:long_note).permit(:title, :description, :publicly_displayed, images: [])
  end
end

app/views/long_notes/_form.html.erb
<%= simple_form_for @long_note do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :title %>
  <%= f.label :description %>
  <%= f.rich_text_area :description %>
  <%#= f.hidden :images, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/long_notes/_show.html.erb
<div class="my-card">
  <p>Note crée le
    <em>
      <%= @long_note.created_at.day %>
      of
      <%= I18n.t('date.month_names')[@long_note.created_at.month] %>
      <%= @long_note.created_at.year %> -
    </em>
    Modifiée pour la dernière fois le
    <em>
      <%= @long_note.updated_at.day %>
      of
      <%= I18n.t('date.month_names')[@long_note.updated_at.month] %>
      <%= @long_note.updated_at.year %> :
    </em>
    <strong><%= @long_note.title %></strong>
  </p>
  <p><%= @long_note.description %></p>
  <% @long_note.images.each do |image| %>
    <%= cl_image_tag image.key, crop: :fill %>
  <% end %>
  <div class="action-box">
    <div class="action">
      <% if policy(@long_note).edit? %>
        <%= link_to edit_long_note_path(@long_note) do %>
          <i class="far fa-edit"></i>
        <% end %>
      <% end %>
    </div>
    <div class="action">
      <% if policy(@long_note).destroy? %>
        <%= link_to @long_note, method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="action-box">
    <div class="action" data-long_note-id="<%= @long_note.id %>">
      <% if @long_note.publicly_displayed %>
        <% if policy(@long_note).set_public? %>
          <%= link_to long_note_set_public_path(@long_note), method: :patch do %>
            <i class="fas fa-check"></i> Publique :
          <% end %>
        <% end %>
    </div>
    <div class="action">
      <%= link_to long_note_path(@long_note) do %>
        <i class="fas fa-link"></i> <%= show_url(@long_note) %>
      <% end %>
    </div>
    <div class="action">
      <% else %>
        <% if policy(@long_note).set_public? %>
          <%= link_to long_note_set_public_path(@long_note), method: :patch do %>
            <i class="fas fa-times"></i> Privé
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/long_notes/index.html.erb
<div class="flex-wrap mb-5">
  <div class="title">
    <h4>Long Notes</h4>
    <div class="action">
      <% if policy(LongNote).create? %>
        <%= link_to new_long_note_path do %>
          <i class="far fa-plus-square"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="">
    <%= form_tag long_notes_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-bar",
        placeholder: "Entrer un mot clé"
      %>
      <%= submit_tag "Chercher", class: "btn button" %>
    <% end %>
  </div>
</div>

<div class="one-quarter-wrapper">
  <p><%= @message %></p>
  <% if @long_notes.any? %>
    <div class="one-third">
      <% @long_notes.each do |long_note|%>
        <div class="long_note">
          <%= link_to long_notes_path(id: long_note.id) do %>
            <p>
              <strong>
                <%= I18n.t('date.month_names')[long_note.updated_at.month] %>
                <%= long_note.updated_at.year %> :
              </strong>
            <br>
              <em><%= long_note.title %></em>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="two-third">
      <%= render 'show' %>
    </div>
  <% end %>
</div>

          <%# if params[:query] %>
            <!-- <p>
              <%#= long_note.description %>
            </p> -->
          <%# end %>

app/views/long_notes/show.html.erb
<%= render 'show' %>