config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  patch 'edit_color_preference', to: 'users#edit_color_preference'
  root to: 'pages#home'

  resources :to_do_lists, except: [ :show ] do
    resources :tasks, only: [ :new, :create ]
  end

  resources :tasks, only: [ :destroy, :edit, :update ] do
    patch 'done', to: 'tasks#done'
  end

  resources :long_notes do
    patch 'set_public', to: 'long_notes#set_public'
  end

  resources :objectives
  # resources :missions
  resources :short_notes
  resources :bookmarks
  resources :posts
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :to_do_list

  validates :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]

  def new
    @to_do_list = ToDoList.find(params[:to_do_list_id])
    @task = Task.new
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    @task.to_do_list_id = params[:to_do_list_id]
    authorize @task
    if @task.save
      redirect_to to_do_lists_path
    else
      render 'to_do_lists'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to to_do_lists_path
    else
      render 'to_do_lists'
    end
  end

  def done
    @task = Task.find(params[:task_id])
    authorize @task
    if @task.update_attribute(:status, status)
      redirect_to to_do_lists_path, notice: if @task.status then "Rock star !" else "Tomorrow is another day !" end
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to to_do_lists_path
  end

  private

  def status
    @task.status ? @task.status = false : @task.status = true
  end

  def set_task
    @task = Task.find(params[:id])
    authorize @task
  end

  def task_params
    params.require(:task).permit(:description, :status, :to_do_list_id)
  end
end

app/views/tasks/_form.html.erb
<%= simple_form_for([@to_do_list, @task]) do |f| %>
  <%= f.input :description %>
   <%= f.input :status, as: :boolean, checked_value: true, unchecked_value: false %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/tasks/_show.html.erb
<div class="task-wrap" data-task-id="<%= task.id %>">
  <div class="check">
    <% if task.status %>
      <%= link_to task_done_path(task), method: :patch do %>
        <span class=""><i class="far fa-check-square"></i></span>
      <% end %>
    <% else %>
      <%= link_to task_done_path(task), method: :patch do %>
        <span class=""><i class="far fa-square"></i></span>
      <% end %>
    <% end %>
  </div>
  <div class="task-description">
    <% if policy(task).edit? %>
      <%= link_to  edit_task_path(task) do %>
        <%= task.description %>
      <% end %>
    <% end %>
  </div>
  <div class="action">
    <% if policy(task).destroy? %>
      <%= link_to task_path(task), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    <% end %>
  </div>
</div>