config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  patch 'edit_color_preference', to: 'users#edit_color_preference'
  root to: 'pages#home'

  resources :to_do_lists, except: [ :show ] do
    resources :tasks, only: [ :new, :create ]
  end

  resources :tasks, only: [ :destroy, :edit, :update ] do
    patch 'done', to: 'tasks#done'
  end

  resources :long_notes do
    patch 'set_public', to: 'long_notes#set_public'
  end

  resources :objectives
  # resources :missions
  resources :short_notes
  resources :bookmarks
  resources :posts
end

app/views/shared/_colorpins.html.erb
<div class="bg-list">
  <%= link_to edit_color_preference_path(color_preference: 'claret'), method: :patch do %>
    <div class="bg-color-pin claret"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'persianplum'), method: :patch do %>
    <div class="bg-color-pin persianplum"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'darkchocolate'), method: :patch do %>
    <div class="bg-color-pin darkchocolate"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'darkjunglegreen'), method: :patch do %>
    <div class="bg-color-pin darkjunglegreen"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'phthalogreen'), method: :patch do %>
    <div class="bg-color-pin phthalogreen"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'prussianblue'), method: :patch do %>
    <div class="bg-color-pin prussianblue"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'darkblue'), method: :patch do %>
    <div class="bg-color-pin darkblue"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'oxfordblue'), method: :patch do %>
    <div class="bg-color-pin oxfordblue"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'darkoxfordblue'), method: :patch do %>
    <div class="bg-color-pin darkoxfordblue"></div>
  <% end %>
  <%= link_to edit_color_preference_path(color_preference: 'darkpurple'), method: :patch do %>
    <div class="bg-color-pin darkpurple"></div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-secondary alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_right-bar.html.erb
<div class="tools-icon">
  <%= image_tag "tools.png", alt: "tools" %>
</div>
<div class="right-bar">
  <div class="username">
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "You are signing out. Are you sure?" } do %>
        <p><%= current_user.username %></p>
      <% end %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
  <%= render 'shared/tools' %>
</div>

app/views/shared/_right_bar.html.erb
<div class="right-bar">
  <div class="username">
    <p>Sandra</p>
  </div>
  <div class="percent">
    <p>24%</p>
    <div class="field">
      <div class="text-field">

      </div>
      <div class="icon">
        <i class="far fa-play-circle"></i>
      </div>
    </div>
    <div class="result">
      <p>953€</p>
    </div>
  </div>
  <div class="chrono">
    <div class="controls">
      <i class="far fa-play-circle"></i>
      <i class="far fa-stop-circle"></i>
    </div>
    <div class="chrono-image">
      <%= image_tag "stopwatch.png", alt: "chrono" %>
    </div>
  </div>
  <div class="rule-of-eight">
    <p>Rule of Eight</p>
    <div class="field">
      <div class="text-field">

      </div>
      <div class="icon">
        <i class="far fa-play-circle"></i>
      </div>
    </div>
    <div class="result">
      <p>63,15</p>
      <i class="far fa-times-circle"></i>
    </div>
    <div class="field">
      <div class="text-field">

      </div>
      <div class="icon">
        <i class="far fa-play-circle"></i>
      </div>
    </div>
    <div class="result">
      <p>32</p>
      <i class="far fa-check-circle"></i>
    </div>
  </div>
</div>

app/views/shared/_tools.html.erb
<!-- <div class="percent box">
  <p>URSSAF - 24%</p>
  <div class="field">
    <div class="text-field">
      <input id="percent" type="number">
    </div>
    <div class="icon">
      <i id="go-percent" class="far fa-play-circle"></i>
    </div>
  </div>
  <div id="result-percent" class="result">
  </div>
</div> -->
<div class="chrono box">
  <p class="mb-0">Chrono</p>
  <div class="controls">
    <i id="start" class="far fa-play-circle"></i>
    <i id="stop" class="far fa-stop-circle"></i>
    <div id="chrono-result" class="result"></div>
  </div>
  <div class="clock">
    <div class="clock-face">
      <div class="hand hour-hand"></div>
      <div class="hand min-hand"></div>
      <div class="hand second-hand"></div>
      <div class="clock-numbers">
        <div class="clock-hour un">1</div>
        <div class="clock-hour deux">2</div>
        <div class="clock-hour trois">3</div>
        <div class="clock-hour quatre">4</div>
        <div class="clock-hour cinq">5</div>
        <div class="clock-hour six">6</div>
        <div class="clock-hour sept">7</div>
        <div class="clock-hour huit">8</div>
        <div class="clock-hour neuf">9</div>
        <div class="clock-hour dix">10</div>
        <div class="clock-hour onze">11</div>
        <div class="clock-hour douze">12</div>
      </div>
    </div>
  </div>
</div>
<div class="rule-of-eight box">
  <p>Rule of Eight</p>
  <div class="field">
    <div id="result-sign"></div>
    <div class="text-field">
      <input id="input-eight" type="number">
    </div>
    <div class="icon">
      <i id="go-eight" class="far fa-play-circle"></i>
    </div>
  </div>
  <div id="result-eight" class="result"></div>
</div>
<div class="hex box">
  <p>RGB to HEX</p>
  <div class="field">
    <div class="text-field rgb">
      <label name="R">R</label>
      <input type="number" id="R" maxlength="3">
      <label name="G">G</label>
      <input type="number" id="G" maxlength="3">
      <label>B</label>
      <input type="number" id="B" maxlength="3">
    </div>
  </div>
  <div class="icon">
    <i id="go-hex" class="far fa-play-circle"></i>
  </div>
  <div id="result-hex" class="result">
    <div class="color-hex" style="background-color: <%= rgb(33, 24, 49) %>"></div>
      <%= rgb(33, 24, 49) %>
    </div>
</div>

app/views/shared/_top-bar.html.erb
<div class="top-bar">
  <ul class="top-menu">
    <li class="logo">
      <%= link_to "/" do %>
        <%= image_tag "logo.png", alt: "logo-bat" %>
      <% end %>
    </li>
    <li>
      <%= link_to to_do_lists_path, class: "menu-item #{'active' if params[:controller] == 'to_do_lists'}" do %>
        <%= image_tag "list_gray.png", alt: "list" %>
      <% end %>
    </li>
    <li>
      <%= link_to long_notes_path, class: "menu-item #{"active" if params[:controller] == "long_notes" }" do %>
        <%= image_tag "notebook_gray.png", alt: "notebook" %>
      <% end %>
    </li>
    <li>
      <%= link_to posts_path, class: "menu-item #{"active" if params[:controller] == "posts" }" do %>
        <%= image_tag "writing-gray.png", alt: "journal" %>
      <% end %>
    </li>
    <li>
      <%= link_to bookmarks_path, class: "menu-item #{"active" if params[:controller] == "bookmarks" }" do %>
        <%= image_tag "bookmark-gray.png", alt: "bookmark" %>
      <% end %>
    </li>
    <li>
      <%= link_to short_notes_path, class: "menu-item #{"active" if params[:controller] == "short_notes" }" do %>
        <%= image_tag "post-it_gray.png", alt: "post-it" %>
      <% end %>
    </li>
    <li>
      <%= link_to objectives_path, class: "menu-item #{"active" if params[:controller] == "objectives" }" do %>
        <%= image_tag "mission_gray.png", alt: "objectif" %>
      <% end %>
    </li>

    <!-- <li>
      <%#= link_to missions_path, class: "menu-item #{"active" if params[:controller] == "missions" }" do %>
        <%#= image_tag "sketchbook_gray.png", alt: "sketchbook" %>
      <%# end %>
    </li> -->
  </ul>
</div>