config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  patch 'edit_color_preference', to: 'users#edit_color_preference'
  root to: 'pages#home'

  resources :to_do_lists, except: [ :show ] do
    resources :tasks, only: [ :new, :create ]
  end

  resources :tasks, only: [ :destroy, :edit, :update ] do
    patch 'done', to: 'tasks#done'
  end

  resources :long_notes do
    patch 'set_public', to: 'long_notes#set_public'
  end

  resources :objectives
  # resources :missions
  resources :short_notes
  resources :bookmarks
  resources :posts
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: [:edit, :update, :destroy]

  def index
    @to_do_lists = policy_scope(ToDoList).order(created_at: :desc)
  end

  def new
    @to_do_list = ToDoList.new
    @to_do_list.user = current_user
    authorize @to_do_list
  end

  def create
    @to_do_list = ToDoList.new(to_do_list_params)
    @to_do_list.user = current_user
    authorize @to_do_list

    if @to_do_list.save
      redirect_to to_do_lists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @to_do_list.update(to_do_list_params)

    if @to_do_list.save
      redirect_to to_do_lists_path
    else
      render :edit
    end
  end

  def destroy
    @to_do_list.destroy
    redirect_to to_do_lists_path
  end

  private

  def set_to_do_list
    @to_do_list = ToDoList.find(params[:id])
    authorize @to_do_list
  end

  def to_do_list_params
    params.require(:to_do_list).permit(:title)
  end
end

app/views/to_do_lists/_form.html.erb
<%= simple_form_for @to_do_list do |f| %>
  <%= f.input :title %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/to_do_lists/index.html.erb
<div class="title">
  <h4>To do lists</h4>
  <div class="action">
    <% if policy(ToDoList).create? %>
      <%= link_to new_to_do_list_path do %>
        <i class="far fa-plus-square"></i>
      <% end %>
    <% end %>
  </div>
</div>

<div class="grid-3fr-wrapper todos-container">
  <% @to_do_lists.each do |list|%>
    <div class="my-card todos">
      <progress
        value='<%= task_progress(list.tasks.count, list.tasks.where(status: true).count) %>'
        max="100">
      </progress>

      <div class="task-wrap">
        <% if policy(list).edit? %>
          <%= link_to edit_to_do_list_path(list) do %>
            <h4><%= list.title %></h4>
          <% end %>
        <% end %>

        <div class="action">
          <% if policy(list).destroy? %>
            <%= link_to list, method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
      </div>

      <div id="tasks">
        <% list.tasks.order(:status).each do |task| %>
          <%= render 'tasks/show', task: task %>
        <% end %>
      </div>

      <div class="action center">
        <% if policy(Task).create? %>
          <%= link_to new_to_do_list_task_path(list) do %>
            <i class="far fa-plus-square"></i>
          <% end %>
        <% end %>
      </div>

    </div>
  <% end %>
</div>